### ISSUE TITLE
Numerous errors on server setup.

### ISSUE THREAD

**Issue by OrionGrant** [pjimenezmateo/kindle-wallpaper#19] opened 2020-06-13 17:01 UTC
I am trying to get set up with this on one of my servers, it seems to kind of work as it looks like it's exporting a yellow done.png file. Here are the errors I'm getting, please help!

`./launch.sh
Traceback (most recent call last):
  File "programs/parse_weather.py", line 33, in <module>
    if os.path.exists(image_path):
NameError: name 'os' is not defined
Traceback (most recent call last):
  File "programs/parse_ical.py", line 1, in <module>
    from icalendar import Calendar
ModuleNotFoundError: No module named 'icalendar'
Error reading SVG:Error opening file /home/user/kindle/server/almost_done.svg: No such file or directory

 | pngcrush 1.7.85
 |    Copyright (C) 1998-2002, 2006-2015 Glenn Randers-Pehrson
 |    Portions copyright (C) 2005       Greg Roelofs
 | This is a free, open-source program.  Permission is irrevocably
 | granted to everyone to use this version of pngcrush without
 | payment of any fee.
 | Executable name is pngcrush
 | It was built with libpng version 1.6.21, and is
 | running with  libpng version 1.6.34 - September 29, 2017

 |    Copyright (C) 1998-2004, 2006-2015 Glenn Randers-Pehrson,
 |    Copyright (C) 1996, 1997 Andreas Dilger,
 |    Copyright (C) 1995, Guy Eric Schalnat, Group 42 Inc.,
 | and zlib version 1.2.8, Copyright (C) 1995-2013,
 |    Jean-loup Gailly and Mark Adler.
Warning: versions are different between png.h and png.c
  png.h version: 1.6.21
  png.c version: 1.6.34

 | It was compiled with gcc version 5.3.1 20160421.

While measuring IDATs in almost_done.png pngcrush caught libpng error:
   Read Error: invalid length returned

   Recompressing IDAT chunks in almost_done.png
   Total length of data found in critical chunks           =         0
Could not find file: done.png
   CPU time decoding 0.000, encoding 0.000, other 0.000, total 0.000 sec.

rm: cannot remove '/var/www/kindle/done.png': No such file or directory
mv: cannot stat 'done.png': No such file or directory
rm: cannot remove 'basic.ics': No such file or directory
rm: cannot remove 'after-weather.svg': No such file or directory
rm: cannot remove 'almost_done.svg': No such file or directory`

**Comment by OrionGrant** [comment] 2020-06-13 17:02
Never mind, there is no done.png at all. Not sure what's going on.

**Comment by pjimenezmateo** [comment] 2020-06-13 17:10
I just checked, it seems that the os import is missing, could you add the following line on the top of the programs/parseweather.py?

```
import os
```

Additionally you are missing the icalendar dependency, you should be able to install it by executing the following commands:

```
sudo apt install python3-pip
pip install icalendar
```

Let me know if that fixes it, let me fix the code in the meantime.

**Comment by OrionGrant** [comment] 2020-06-13 17:21
sudo apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 218 not upgraded.

**Comment by OrionGrant** [comment] 2020-06-13 17:22
~/kindle/server$ ./launch.sh
icons/500d.svg
Traceback (most recent call last):
  File "programs/parse_ical.py", line 1, in <module>
    from icalendar import Calendar
ModuleNotFoundError: No module named 'icalendar'
Error reading SVG:Error opening file /home/user/kindle/server/almost_done.svg: No such file or directory

**Comment by OrionGrant** [comment] 2020-06-13 17:23
I've added the import os line, I get the above result. Looks like icalendar dependencies are satisfied, so not sure what is going on.

**Comment by pjimenezmateo** [comment] 2020-06-13 17:23
You missed the following command:

```
pip install icalendar
```

Try that first and then run again.

**Comment by OrionGrant** [comment] 2020-06-13 17:26
Collecting icalendar
  Using cached https://files.pythonhosted.org/packages/20/f2/f600e9aa510ab6e052b0344d7f3a4d6124229c74a922d8dea9b15e1aaf2b/icalendar-4.0.6-py2.py3-none-any.whl
Collecting pytz (from icalendar)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting python-dateutil (from icalendar)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->icalendar)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: pytz, six, python-dateutil, icalendar
Successfully installed icalendar-4.0.6 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0

**Comment by OrionGrant** [comment] 2020-06-13 17:27
same result, launch.sh returns this:

icons/500d.svg
Traceback (most recent call last):
  File "programs/parse_ical.py", line 1, in <module>
    from icalendar import Calendar
ModuleNotFoundError: No module named 'icalendar'
Error reading SVG:Error opening file /home/user/kindle/server/almost_done.svg: No such file or directory

**Comment by pjimenezmateo** [comment] 2020-06-13 17:28
Ok, I think I know what the problem is. I think you have the Python 2.x version of pip installed as well. Run the following:

```
python3 -m pip install icalendar
```

That should install the python3 version of icalendar.

**Comment by OrionGrant** [comment] 2020-06-13 18:05
Perfect, working great, thank you!

**Comment by OrionGrant** [comment] 2020-06-13 18:05
Any chance I can add more than one calendar?

**Comment by pjimenezmateo** [comment] 2020-06-13 18:08
Great, I'm glad I could help.

Regarding your question, it should be possible by modifying the parse_ical.py file and reading more than one ical instead of one.

Unfortunately I do not have the time to implement this, but if you want to go ahead and try I will be more than happy to assist.

I'm closing this issue, open a new one for anything else you may need.

**Closed** 2020-06-13 18:09 UTC
